version: "3"

services:
  todo-list-app:
    container_name: todo-list-app
    # network_mode: todo_list_network
    image: todo_list_app
    ports:
      - 3000:3000
    environment:
      NUXT_PUBLIC_API_BASE: http://localhost:3002
